---
driver:
   name: vagrant

driver_config:
  customize:
    memory: 3072

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

provisioner:
  data_path: test

platforms:
- name: centos-6.5
  attributes:
    mongodb:
      reload_action: "reload"
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  - recipe[authbind]
- name: debian-7.6
  run_list:
  - recipe[apt]
  - recipe[authbind]

suites:
  - name: default
    attributes:
      machine_fqdn: graylog2.local
      machine_fqdn_as_hostname: true
      graylog2:
        password_secret: "2jueVqZpwLLjaWxV"
        root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        web:
          secret: "2jueVqZpwLLjaWxV"
        restart: "immediately"
        rest:
          admin_access_token: "F3DenL9HXW12KECdLmrfQ8HNGW4zwbwlJSyo7PxlsgHvgeay5F3tQhnoH6T2G7X3iiy2bcYPClsjCWi1PIY48sCSSyoW4H64"
        inputs:
          - '{"title": "syslog", "type":"org.graylog2.inputs.syslog.udp.SyslogUDPInput", "creator_user_id":"admin", "global": true, "configuration": { "port": 1514, "allow_override_date": true, "bind_address": "0.0.0.0", "store_full_message": true, "recv_buffer_size": 1048576 }}'
        streams: 
          - '{"title":"Demo Stream","description":"Show all GETs", "creator_user_id":"admin", "rules": [{"field":"message","value":"GET.*","type":2,"inverted":false}, {"field":"message","value":".*/login.*","type":2,"inverted":false}]}'
        dashboards:
          - '{"title": "Demo SSH Dashboard", "description": "SSH related widgets", "creator_user_id": "admin", "widgets": [ { "description": "SSH messages", "config": { "interval": "minute", "query": "*", "range_type": "relative", "range": "0" }, "type": "search_result_chart", "creator_user_id": "admin" }, { "description": "No. SSH logins", "config": { "query": "message:sshd AND message:opened", "range_type": "relative", "range": "0" }, "type": "search_result_count", "creator_user_id": "admin" } ] }'
      elasticsearch:
        version: "0.90.10"
        cluster:
          name: "graylog2"
    run_list:
      - recipe[fqdn]
      - recipe[mongodb]
      - recipe[elasticsearch]
      - recipe[graylog2]
      - recipe[graylog2::server]
      - recipe[graylog2::web]
      - recipe[graylog2::radio]
      - recipe[graylog2::authbind]
