---
driver:
   name: vagrant

driver_config:
  customize:
    memory: 3072

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

provisioner:
  data_path: test

platforms:
- name: centos-6.5
  attributes:
    mongodb:
      reload_action: "reload"
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  - recipe[authbind]
- name: debian-7.6
  run_list:
  - recipe[apt]
  - recipe[authbind]

suites:
  - name: default
    attributes:
      machine_fqdn: graylog2.local
      machine_fqdn_as_hostname: true
      graylog2:
        password_secret: "2jueVqZpwLLjaWxV"
        root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        web:
          secret: "2jueVqZpwLLjaWxV"
        restart: "immediately"
      elasticsearch:
        version: "0.90.10"
        cluster:
          name: "graylog2"
    run_list:
      - recipe[fqdn]
      - recipe[mongodb]
      - recipe[elasticsearch]
      - recipe[torch-graylog2]
      - recipe[torch-graylog2::server]
      - recipe[torch-graylog2::web]
      - recipe[torch-graylog2::radio]
      - recipe[torch-graylog2::authbind]
