---
driver:
   name: vagrant

driver_config:
  customize:
    memory: 4096
  network:
    - - forwarded_port
      - guest: 9000
        host: 9000
        auto_correct: true
    - - forwarded_port
      - guest: 12900
        host: 12900
        auto_correct: true
    - - forwarded_port
      - guest: 12201
        host: 12201
        auto_correct: true 

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.8.1'
  data_path: test

platforms:
- name: centos-6.7
  attributes:
    mongodb:
      reload_action: "reload"
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: debian-7.8
  run_list:
  - recipe[apt]

suites:
  - name: default
    attributes:
      machine_fqdn: graylog.local
      machine_fqdn_as_hostname: true
      java:
        jdk_version: '8'
        install_flavor: 'oracle'
        oracle:
          accept_oracle_download_terms: true
      graylog2:
        password_secret: "2jueVqZpwLLjaWxV"
        # Credentials are admin:admin
        root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
        web:
          secret: "2jueVqZpwLLjaWxV"
        restart: "delayed"
        rest:
          transport_uri: 'http://127.0.0.1:12900'
          admin_access_token: "F3DenL9HXW12KECdLmrfQ8HNGW4zwbwlJSyo7PxlsgHvgeay5F3tQhnoH6T2G7X3iiy2bcYPClsjCWi1PIY48sCSSyoW4H64"
      elasticsearch:
        version: "2.2.0"
        cluster:
          name: "graylog"
    run_list:
      - recipe[fqdn]
      - recipe[mongodb]
      - recipe[java]
      - recipe[elasticsearch_test]
      - recipe[graylog2]
      - recipe[graylog2::server]
      - recipe[graylog2::collector]
      - recipe[graylog2::authbind]
